### ISSUE TITLE
Lots of Polygons

### ISSUE THREAD

**Issue by Vandash** [PouletFrit/csDelaunay#4]
Problem when using lots of points :
![voronoibug](https://cloud.githubusercontent.com/assets/8964232/22183181/34556d96-e0b8-11e6-9ca0-56782ac9f44a.jpg)

It might be related with this code in Voronoi.cs :
`if (region.Count < 1)
					{
						site = sites.Next();
						continue;
					}`

Also seems to amplify when clearing / regenerating voronoi diagrams

not fix yet to propose..!

**Comment by Vandash** [comment]
Fixed!

Problem wasn't in the lib, it was just that I was initializing Voronoi with a list of points created randomly using Range(int, int) and beyond a certain amount of points they started colliding with each other. I then had an issue when trying to perform Edge.CreateBisectingEdge where dx = dy = 0

End of story ;)

**Comment by cjburkey01** [comment]
Could you mark this as closed?
